# Generated by Django 3.1.1 on 2020-09-13 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('purpose', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('date_of_request', models.DateField()),
                ('created_on', models.DateField(auto_now=True)),
                ('status', models.CharField(max_length=50)),
                ('excel_path', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Erf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('purpose', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('date_of_request', models.DateField()),
                ('created_on', models.DateField(auto_now=True)),
                ('status', models.CharField(max_length=50)),
                ('excel_path', models.FileField(upload_to='uploads/')),
                ('arf', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rems_api.arf')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lodging', models.IntegerField()),
                ('me', models.IntegerField()),
                ('created_on', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField()),
                ('amount', models.IntegerField()),
                ('created_on', models.DateField(auto_now=True)),
                ('arf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rems_api.arf')),
                ('erf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rems_api.erf')),
            ],
        ),
        migrations.CreateModel(
            name='Me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.TextField()),
                ('no_of_nights', models.SmallIntegerField()),
                ('daily_rate', models.IntegerField()),
                ('percentage_of_daily_rate', models.SmallIntegerField()),
                ('created_on', models.DateField(auto_now=True)),
                ('arf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rems_api.arf')),
                ('erf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rems_api.erf')),
            ],
        ),
        migrations.AddField(
            model_name='erf',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rems_api.location'),
        ),
        migrations.AddField(
            model_name='erf',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arf',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rems_api.location'),
        ),
        migrations.AddField(
            model_name='arf',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
