# Generated by Django 3.1.1 on 2020-09-13 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rems_api', '0002_auto_20200913_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='me',
            name='arf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes', to='rems_api.arf'),
        ),
        migrations.AlterField(
            model_name='me',
            name='erf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mes', to='rems_api.erf'),
        ),
        migrations.AlterField(
            model_name='othercost',
            name='arf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_costs', to='rems_api.arf'),
        ),
    ]
