# Generated by Django 3.1.1 on 2020-09-14 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rems_api', '0005_auto_20200914_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='me',
            name='lodging',
        ),
        migrations.CreateModel(
            name='Lodging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.TextField()),
                ('no_of_nights', models.SmallIntegerField()),
                ('daily_rate', models.IntegerField()),
                ('percentage_of_daily_rate', models.SmallIntegerField()),
                ('created_on', models.DateField(auto_now=True)),
                ('arf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lodgings', to='rems_api.arf')),
                ('erf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lodgings', to='rems_api.erf')),
            ],
        ),
    ]
