# Generated by Django 3.1.1 on 2020-09-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rems_api', '0006_auto_20200914_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arf',
            name='excel_path',
        ),
        migrations.RemoveField(
            model_name='erf',
            name='excel_path',
        ),
        migrations.AddField(
            model_name='arf',
            name='excel_sheet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='erf',
            name='excel_sheet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
