# Generated by Django 3.1.1 on 2020-09-21 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rems_api', '0010_auto_20200921_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arf',
            name='location',
        ),
        migrations.AddField(
            model_name='arf',
            name='location_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rems_api.location'),
        ),
    ]
