# Generated by Django 3.1.1 on 2020-09-21 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rems_api', '0011_auto_20200921_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arf',
            old_name='location_id',
            new_name='location',
        ),
    ]
