# Generated by Django 3.1.1 on 2020-10-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rems_api', '0012_auto_20200921_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodging',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='me',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='othercost',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
