# Generated by Django 3.1.1 on 2020-10-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rems_api', '0013_auto_20201010_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lodging',
            old_name='date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='me',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='lodging',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='me',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
