# Generated by Django 3.1.1 on 2020-10-14 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rems_api', '0014_auto_20201014_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erf',
            name='arf',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erf', to='rems_api.arf'),
        ),
    ]
