# Generated by Django 3.1.1 on 2020-10-16 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rems_api', '0016_auto_20201014_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodging',
            name='erf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lodgings', to='rems_api.erf'),
        ),
        migrations.AlterField(
            model_name='me',
            name='erf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes', to='rems_api.erf'),
        ),
        migrations.AlterField(
            model_name='othercost',
            name='arf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_costs', to='rems_api.arf'),
        ),
        migrations.AlterField(
            model_name='othercost',
            name='erf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rems_api.erf'),
        ),
    ]
