# Generated by Django 3.1.1 on 2020-11-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rems_api', '0018_auto_20201016_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodging',
            name='actual_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='percentage_of_daily_rate',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='me',
            name='percentage_of_daily_rate',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
