# Generated by Django 3.1.1 on 2020-11-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rems_api', '0019_auto_20201121_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='me',
            name='no_of_nights',
            field=models.FloatField(),
        ),
    ]
