# Generated by Django 3.1.1 on 2020-11-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rems_api', '0020_auto_20201121_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='days',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
