# Generated by Django 3.1.1 on 2020-11-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rems_api', '0021_me_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='me',
            name='no_of_nights',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
